LOCAL_DIR := $(GET_LOCAL_DIR)
TARGET := pine
MODULES += app/mt_boot \
           dev/lcm
MTK_EMMC_SUPPORT = yes
DEFINES += MTK_NEW_COMBO_EMMC_SUPPORT
MTK_KERNEL_POWER_OFF_CHARGING = yes
MTK_LCM_PHYSICAL_ROTATION = 180
CUSTOM_LK_LCM="r6135otp_hd720_dsi_vdo r6135_hd720_dsi_vdo nt35521s_hd720_dsi_vdo"
#hx8392a_dsi_cmd = yes
#FASTBOOT_USE_G_ORIGINAL_PROTOCOL = yes
MTK_SECURITY_SW_SUPPORT = no
MTK_VERIFIED_BOOT_SUPPORT = no
MTK_SEC_FASTBOOT_UNLOCK_SUPPORT = no
DEBUG := 0
BOOT_LOGO = cu_lte_hd720
#DEFINES += WITH_DEBUG_DCC=1
DEFINES += WITH_DEBUG_UART=1
#DEFINES += WITH_DEBUG_FBCON=1
#DEFINES += MACH_FPGA=y
#DEFINES += SB_LK_BRINGUP=y
DEFINES += MTK_GPT_SCHEME_SUPPORT
MTK_GOOGLE_TRUSTY_SUPPORT=no
